### ISSUE TITLE
Error handling mixed primitive / object nested items (stdClass as array)

### ISSUE THREAD

**Issue by CJLees01** [tonirilix/nested-json-flattener#9]
The conversion will fail for a JSON like the following, where the nested array has a combination of a primitive (string), and an object/array.

```
{
  "information_on_instrument": [
    "With_ISIN",
    {
      "instrument_identifier": "IT0001233417",
      "currency": "EUR"
    }
  ]
}
```

The reason appears to be a short-cut in `flatArray()` method in Flattener class, which checks only the type of the first data item and makes an assumption about subsequent items. In this edge case, it sees the first value is a string, and therefore tries to join all of the items as strings, but this fails because the second item in the array is an object.

Will try to find a little time to make a pull request to fix.

**Comment by tonirilix** [comment]
Hi @CJLees01 
At the moment I'm a little busy with a project but I could try to find a moment to check it on weekend but if you already have the fix feel free to send a pull request and I'll merge it.

Thanks for the feedback! 🎉

**Comment by CJLees01** [comment]
See pull request #10

**Comment by tonirilix** [comment]
Sorry for the late response, I was out for some small vacations.

Thanks a lot for your contribution! 
I'll test it later today and will merge as soon as possible.
